#!/usr/bin/env node
/**
 * update-memory.mjs
 *
 * Updates Claude AI memory files with current project state.
 * Run via: npm run memory:update
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, join } from 'path';
import { homedir } from 'os';

const MEMORY_DIR = join(
  homedir(),
  '.claude/projects/-Users-dushyantpant-Desktop-Personal-Project-invent/memory'
);

const PROJECT_ROOT = resolve(new URL('.', import.meta.url).pathname, '..');

// ─── Helpers ────────────────────────────────────────────────────────────────

function run(cmd, fallback = '') {
  try {
    return execSync(cmd, { cwd: PROJECT_ROOT, encoding: 'utf8' }).trim();
  } catch {
    return fallback;
  }
}

function readMemory(filename) {
  const path = join(MEMORY_DIR, filename);
  return existsSync(path) ? readFileSync(path, 'utf8') : '';
}

function writeMemory(filename, content) {
  const path = join(MEMORY_DIR, filename);
  writeFileSync(path, content, 'utf8');
  console.log(`  Updated: ${filename}`);
}

function ensureMemoryDir() {
  if (!existsSync(MEMORY_DIR)) {
    mkdirSync(MEMORY_DIR, { recursive: true });
    console.log(`  Created memory directory: ${MEMORY_DIR}`);
  }
}

// ─── Project state collectors ────────────────────────────────────────────────

function getGitInfo() {
  return {
    branch: run('git branch --show-current', 'unknown'),
    lastCommit: run('git log -1 --pretty=format:"%h %s" HEAD', 'unknown'),
    recentCommits: run('git log --oneline -10', ''),
    status: run('git status --short', ''),
  };
}

function getPackageVersion() {
  try {
    const pkg = JSON.parse(readFileSync(join(PROJECT_ROOT, 'package.json'), 'utf8'));
    return pkg.version ?? '0.0.0';
  } catch {
    return 'unknown';
  }
}

function getScripts() {
  try {
    const pkg = JSON.parse(readFileSync(join(PROJECT_ROOT, 'package.json'), 'utf8'));
    return Object.entries(pkg.scripts ?? {})
      .map(([k, v]) => `  "${k}": "${v}"`)
      .join('\n');
  } catch {
    return '';
  }
}

function getArchCheckOutput() {
  return run('node scripts/arch-check.mjs 2>&1', 'arch-check could not run');
}

function countFiles(pattern) {
  return run(`find src -name "${pattern}" | wc -l | tr -d ' '`, '?');
}

// ─── Build the changes entry ─────────────────────────────────────────────────

function buildChangesEntry(git) {
  const today = new Date().toISOString().slice(0, 10);
  return `
## Memory update — ${today}

**Branch:** ${git.branch}
**Last commit:** ${git.lastCommit}

### Recent commits
\`\`\`
${git.recentCommits}
\`\`\`
`;
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main() {
  console.log('\nUpdating Claude memory files...\n');

  ensureMemoryDir();

  const git = getGitInfo();
  const today = new Date().toISOString().slice(0, 10);
  const version = getPackageVersion();
  const archOutput = getArchCheckOutput();
  const tsFiles = countFiles('*.ts');
  const tsxFiles = countFiles('*.tsx');

  // ── 1. Update MEMORY.md current state section ──────────────────────────────
  let memory = readMemory('MEMORY.md');

  // Replace the "Current State" date line
  memory = memory.replace(
    /## Current State \([^)]+\)/,
    `## Current State (${formatMonth(today)})`
  );

  writeMemory('MEMORY.md', memory);

  // ── 2. Append to changes.md ────────────────────────────────────────────────
  let changes = readMemory('changes.md');
  const entry = buildChangesEntry(git);

  // Avoid duplicate entries for the same day
  if (!changes.includes(`Memory update — ${today}`)) {
    changes = changes + '\n---\n' + entry;
    writeMemory('changes.md', changes);
  } else {
    console.log('  changes.md: entry for today already exists, skipping.');
  }

  // ── 3. Write a snapshot file ───────────────────────────────────────────────
  const snapshot = `# Project Snapshot — ${today}

Generated by \`npm run memory:update\`

## Git

- Branch: ${git.branch}
- Last commit: ${git.lastCommit}
- Uncommitted changes: ${git.status || 'none'}

## Version

${version}

## File counts (src/)

- TypeScript files (.ts): ${tsFiles}
- TypeScript React files (.tsx): ${tsxFiles}

## npm scripts

\`\`\`json
${getScripts()}
\`\`\`

## Architecture check output

\`\`\`
${archOutput}
\`\`\`

## Recent commits

\`\`\`
${git.recentCommits}
\`\`\`
`;

  writeMemory('snapshot.md', snapshot);

  console.log('\nDone. Memory files updated at:');
  console.log(`  ${MEMORY_DIR}\n`);
}

function formatMonth(isoDate) {
  const d = new Date(isoDate);
  return d.toLocaleString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' });
}

main();
